theme = "catppuccin_macchiato"


[editor]
auto-pairs = false
bufferline = "always"
line-number = "relative"
# trim-final-newlines = true
trim-trailing-whitespace = true

# [editor.auto-save]
# after-delay.enable = true

[editor.cursor-shape]
normal = "block"
select = "underline"
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"

[keys.normal]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
X = "select_line_above"

[keys.insert]
A-down = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "insert_mode"]
A-up = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "insert_mode"]
